version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: lpg-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lpg-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d lpg-postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: