service: sls-artifact-template-nestjs
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  architecture: arm64
  httpApi:
    binaryMediaTypes:
      - application/octet-stream
      - image/*
      - application/pdf
      - application/zip
      - application/x-zip-compressed
      - video/*
      - audio/* 
  environment:
    NODE_OPTIONS: --enable-source-maps
    DATABASE_HOST: 143.198.193.124
    DATABASE_PORT: 5432
    DATABASE_USERNAME: "jay"
    DATABASE_PASSWORD: "jk3oxf1e99BvY2Ns8v825eU9o34B4BD5LX"
    DATABASE_NAME: "jay_dev"
    # S3 Configuration
    S3_BUCKET_NAME: sls-artifact-template-nestjs-dev-files
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::sls-artifact-template-nestjs-dev-files
            - arn:aws:s3:::sls-artifact-template-nestjs-dev-files/*

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node20
    platform: node
    outdir: dist
    external:
      - '@nestjs/microservices'
      - '@nestjs/websockets'
      - 'class-transformer'
      - 'class-validator'
