import { Module } from '@nestjs/common';
import { HealthModule } from './health/health.module';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import databaseConfig from './config/database.config';
import s3Config from './config/s3.config';
import lineAuthConfig from './config/line-auth.config';
import { FileModule } from './modules/file/file.module';
import { CommodityModule } from './modules/commodity/commodity.module';
import { CustomerModule } from './modules/customer/customer.module';
import { DeliveryModule } from './modules/delivery/delivery.module';
import { RegisterModule } from './modules/register/register.module';
import { OrderModule } from './modules/order/order.module';
import { LineAuthModule } from './modules/line-auth/line-auth.module';
import { LiffModule } from './modules/liff/liff.module';
import {
  AddressBinding,
  BillOfSaleWork,
  BlockUser,
  Check,
  CisCylinderMortgage,
  CisGasPrice,
  CisInitArrearsRecords,
  CisOweCylinderWork,
  CisRefundGas,
  CisWallet,
  Commodity,
  CommodityPhotos,
  CommodityPrice,
  Courier,
  Customer,
  CustomerAddress,
  CustomerArrearsSummary,
  CustomerCheckList,
  CustomerContactPhone,
  CustomerCylinderSummary,
  CustomerDelivery,
  CustomerInSuppliers,
  CustomerRecord,
  Cylinder,
  CylinderAction,
  CylinderActionAlarm,
  CylinderAlarm,
  CylinderFactory,
  CylinderFactoryServices,
  CylinderPrice,
  Delivery,
  DeliveryAddress,
  Device,
  ElectronicOrder,
  ErrorCode,
  GasCylinder,
  GasPrice,
  GroupPrivilege,
  Invoice,
  InvoiceDiscount,
  InvoiceNormalDevice,
  InvoiceOrder,
  LowGasAlert,
  MixedExpense,
  MixedExpenseType,
  NormalDeviceBill,
  NormalDevicePayup,
  NormalDeviceRecords,
  NormalDeviceSettlementRecords,
  Notification,
  OrderCommodity,
  OrderCylinder,
  OrderGas,
  OrderList,
  OrderPayup,
  OrderPayupWork,
  OrderRecord,
  OrderRefund,
  OrderUsageFee,
  PhoneLoss,
  PhoneRecords,
  Supplier,
  SupplierToken,
  TakeBackCylinderWork,
  ThirdPartyApiKey,
  User,
  UserGroup,
  UserSetting,
  WaveinDevice,
  WaveinDeviceAlert,
  WaveinDeviceRecord,
  WaveinTransmitter,
  WaveinTransmitterAlert,
  WorkOrder,
  WorkOrderBill,
  WorkOrderBillPayup,
  WorkOrderCylinder,
  WorkOrderItem,
} from '@artifact/lpg-api-service';

@Module({
  imports: [
    ConfigModule.forRoot({ isGlobal: true, load: [databaseConfig, s3Config, lineAuthConfig] }),
    TypeOrmModule.forRootAsync({
      inject: [ConfigService],
      useFactory: (cs: ConfigService) => {
        const c = cs.get('database');
        console.log(c);
        return {
          type: 'postgres',
          host: c.host,
          port: c.port,
          username: c.username,
          password: c.password,
          database: c.database,
          autoLoadEntities: true,
          entities: [
            AddressBinding,
            BillOfSaleWork,
            BlockUser,
            Check,
            CisCylinderMortgage,
            CisGasPrice,
            CisInitArrearsRecords,
            CisOweCylinderWork,
            CisRefundGas,
            CisWallet,
            Commodity,
            CommodityPhotos,
            CommodityPrice,
            Courier,
            Customer,
            CustomerAddress,
            CustomerArrearsSummary,
            CustomerCheckList,
            CustomerContactPhone,
            CustomerCylinderSummary,
            CustomerDelivery,
            CustomerInSuppliers,
            CustomerRecord,
            Cylinder,
            CylinderAction,
            CylinderActionAlarm,
            CylinderAlarm,
            CylinderFactory,
            CylinderFactoryServices,
            CylinderPrice,
            Delivery,
            DeliveryAddress,
            Device,
            ElectronicOrder,
            ErrorCode,
            GasCylinder,
            GasPrice,
            GroupPrivilege,
            Invoice,
            InvoiceDiscount,
            InvoiceNormalDevice,
            InvoiceOrder,
            LowGasAlert,
            MixedExpense,
            MixedExpenseType,
            NormalDeviceBill,
            NormalDevicePayup,
            NormalDeviceRecords,
            NormalDeviceSettlementRecords,
            Notification,
            OrderCommodity,
            OrderCylinder,
            OrderGas,
            OrderList,
            OrderPayup,
            OrderPayupWork,
            OrderRecord,
            OrderRefund,
            OrderUsageFee,
            PhoneLoss,
            PhoneRecords,
            Supplier,
            SupplierToken,
            TakeBackCylinderWork,
            ThirdPartyApiKey,
            User,
            UserGroup,
            UserSetting,
            WaveinDevice,
            WaveinDeviceAlert,
            WaveinDeviceRecord,
            WaveinTransmitter,
            WaveinTransmitterAlert,
            WorkOrder,
            WorkOrderBill,
            WorkOrderBillPayup,
            WorkOrderCylinder,
            WorkOrderItem,
          ],
          synchronize: false,
        };
      },
    }),
    HealthModule,
    FileModule,
    CommodityModule,
    CustomerModule,
    DeliveryModule,
    RegisterModule,
    OrderModule,
    LineAuthModule,
    LiffModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
